apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-properties
  namespace: confluent
data:
  client.properties: |
    bootstrap.servers=kafka-0.kafka.confluent.svc.cluster.local:9092
    group.id=kafka-validation-group
    client.id=kafka-validation-client
