apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-test
  namespace: confluent
spec:
  ttlSecondsAfterFinished: 86400  # Keep job for 1 day after completion
  template:
    spec:
      containers:
      - name: kafka-test
        image: benediktubuntudev.azurecr.io/kafka_e2e_test:v0.7
        args:
        - "-c"
        - "/tmp/config/client.properties"
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/config
      imagePullSecrets:
      - name: acr-pull-secret
      volumes:
      - name: config-volume
        configMap:
          name: kafka-client-properties
      restartPolicy: Never
  backoffLimit: 2
