apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-tests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ksilin/kafka-test-argo
    targetRevision: HEAD
    path: kafka-test-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true